# path/filename: docker-compose.yml

version: "3"

services:
  controller:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/code:rx
    command: /bin/bash -c "/workspace/docker/run_controller.sh"
    ports:
      - "10000:10000"
    networks:
      - bakllava

  webui:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/code:rx
    command: /bin/bash -c "/workspace/docker/run_webui.sh"
    ports:
      - "11000:11000"
    networks:
      - bakllava
    depends_on:
      - controller

  model_worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: bakllava:latest
    environment:
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN}
    command: /bin/bash -c "/workspace/docker/run_model_worker.sh"
    volumes:
      - .:/code:rx
      - ./models:/models:rwx
    networks:
      - bakllava
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "40000:40000"
    depends_on:
      - controller

networks:
  bakllava:
    external: true
